config/routes.rb
Rails.application.routes.draw do

  root 'equations#main_page'
  post 'equation', to: "equations#handle_input", as: "input"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equations_controller.rb
class EquationsController < ApplicationController
  require 'csv'
  require 'equation_solver'

  def main_page
  end

  def handle_input
    @status = []
    @total_pairs = []
    if params[:a_value] || params[:b_value] || params[:c_value]
      a = params[:a_value]
      b = params[:b_value]
      c = params[:c_value]

      if handle_form(a, b, c)
      else
        return (flash.alert = "One of the requirements for building parabola was not satisfied. Please review the requirements and rectify input values: \nThe value of \"a\" parameter can\'t be nill. \n Input values must be numbers."; redirect_to root_path)
      end

     
    elsif params[:file]
      file = params[:file].read

      if !handle_csv(file)
        return (flash.alert = "Invalid CSV file"; redirect_to root_path)
      else
        @array = handle_csv(file)
      end

      if !add_values(@array)
        return (flash.alert = "An empty file was submitted. Please submit a file with valid values"; redirect_to root_path)
      end

      if count_values(@array)
        @no_common_chart = 1
      end

      if !array_slice(@array)
        return (flash.alert = "Values in the CSV file are split into pairs of three digits where each one corresponds to \"a\", \"b\" and \"c\" parameter to the function. The value of \"a\" parameter can\'t be nill. Please change it to a different digit"; redirect_to root_path)
      end


      render template: "equations/calculate"
    else
      return (flash.alert = "Neither the values for the form nor CSV file were submitted. Please, fill in the form or supply a CSV file with values"; redirect_to root_path)
    end
  end

  private

  def handle_form(a, b, c)
    @status = []
    @total_pairs = []
    result = EquationSolver.calculate(a, b, c, @status)
    if result != false
      @total_pairs << result
    else
        return false
    end
    @no_common_chart = 1
    render template: "equations/calculate"
  end

  def handle_csv(file)
    if !EquationSolver.check_file_validity(file)
      false
    else
      CSV.parse(file).first
    end
  end

  def add_values(array)
    count = @array.count
    if count == 0
      false
    elsif count % 3 != 0
      (3 - (count % 3)).times do
        array << 0
      end
      flash.notice = "The number of values supplied in the CSV file was not divisible by 3, so we added #{3 - (count % 3)} additional elements to be able to build the parabola. The arguments supplied now look as follows: #{@array}"
      array
    else
      array
    end
  end

  def count_values(array)
    if array.count == 3
      true
    else
      false
    end
  end

  def array_slice(array)
    @total_pairs = []
    @array_split = @array.each_slice(3).each_with_index do |pair, i|
      result = EquationSolver.calculate(pair[0], pair[1], pair[2], @status)
      if result != false
        @total_pairs << result
      elsif result == false
        return false
      end
    end
    @total_pairs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/equations/_values.html.erb
  <p>The value of a input is: </p>
  <%= text_field_tag 'a_value', '', class: "form-control"%>
  <br></br>

  <p>The value of b input is: </p>
  <%= text_field_tag 'b_value', '', class: "form-control"%>
  <br></br>

  <p>The value of c input is: </p>
  <%= text_field_tag 'c_value', '', class: "form-control"%>
  <br></br>

app/views/equations/build_from_file.html.erb
<%= @array %>
<%= @array_split %>

app/views/equations/calculate.html.erb
<%= content_tag :div, '', id: "charts_placeholder", data: {parabolas: @total_pairs} %>

<%- unless @no_common_chart %>
  <%= content_tag :div, '', id: "chart_all" do %>
    <p>This is a general chart for all parabolas. This allows for an evaluation of parabola placement against other parabolas. Please, note that the scale of the chart makes parabolas involving large values display only a small portions of them. Each parabola has its own chart below with greater information regarding its vertext and roots.</p> 
    <hr>
  <% end %>
<% end %>

<%- @total_pairs.each_with_index do |pair, index| %>
  <%= content_tag :div, '', id: "chart_#{index}" %>
  <br>
  <br>
  <div id="answer">
    <%= @status[index] %>
  </div>
  <br>
  <br>
  <hr>
  <br>
  <br>    
<% end %>

app/views/equations/main_page.html.erb
<div class="row">
  <div id="form" class="col-md-6">

    <%= form_tag input_path, name: 'equation_form' do%>
      <%= label_tag "Please, enter values for a, b and c inputs: "%>
      <br></br>

      <%= render partial: "values" %>
      <br></br>
      <%= submit_tag 'Submit', disabled: true, class: "btn btn-default" %>
    <% end %>
    <hr>
    <br>
    <p>Alternatively, please select a CSV file to build multiple graphs</p>
    <br>
    <p>Feel free to use the attached CSV template to submit your values and build marvellous parabolas</p>
    <%= link_to('Sample CSV file', '/sample.csv') %>
    <br>
    <br>
    <%= form_tag input_path, multipart: true, class: "form-group" do%>
      <%= file_field_tag :file %>
      <br>
      <br>
      <%= submit_tag "Build the parabolas!", class: "btn btn-default" %>
    <% end %>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Equation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="blog-masthead" id="DIV_1_1">
    <div class="container" id="DIV_2_2">
      <nav class="navbar navbar-inverse">
        <div class="container" id="DIV_1">
          <div class="navbar-header" id="DIV_2">
            <a class="navbar-brand" href= <%=root_path%> id="A_8">Square Equation Parabolizer ;) </a>
          </div>
          <div class="nav navbar-form navbar-right" id="button-header-group">
          </div>
        </div>
      </nav>
    </div>
  </div>

  <div class="container">
    <div class="col-md-12">
      <div id="flash_placeholder">
        <%- if flash[:alert] %>
          <div id='errors' class="alert alert alert-danger">
            <%= flash[:alert] %>
            <br></br>
          </div>
        <% end %>

        <%- if flash[:notice] %>
          <div id='notices' class="notice alert alert-info">
            <%= flash[:notice] %>
            <br></br>
          </div>
        <% end %>
      </div>


      <%= yield %>
    </div>

</body>
</html>